#:schema https://jj-vcs.github.io/jj/latest/config-schema.json
[user]
name = "Vladimir Varankin"
email = "vladimir@varank.in"

[ui]
color = "always"
default-command = "log"
diff-formatter = ":git"
pager = "delta"

[ui.streampager]
show-ruler = false

# https://github.com/jj-vcs/jj/blob/main/cli/src/config/colors.toml
[colors]
change_id = "red"
commit_id = "default"
"commit_id prefix" = { fg = "default", bold = false }
"commit_id rest" = { fg = "default", bold = false }

author = "blue"
committer = "blue"
timestamp = "default"

"bookmark" = "green"
"bookmarks" = "green"
"local_bookmarks" = "green"
"remote_bookmarks" = "green"

"working_copy change_id" = "red"
"working_copy commit_id" = "default"
"working_copy author" = "blue"
"working_copy committer" = "blue"

"diff token" = { underline = false }

[[--scope]]
--when.commands = ["status"]
[--scope.colors]
"diff modified" = "default"

[aliases]
di = ['diff']

[templates]
git_push_bookmark = '"vrnkn/push-" ++ change_id.short()'

[git]
private-commits = "description('private:*')"
