set t_Co=256
"colorscheme xoria256
set background=dark
colorscheme solarized

" Make command line two lines high
set cmdheight=2

set lines=60
set columns=160

set guifont=Monaco:h13

" Don't show toolbar
set guioptions-=T
" Don't show scrolbars
set guioptions-=L
set guioptions-=r
" Use console dialogs for simple choices
set guioptions+=c

" Macvim settings
if has("gui_macvim")
  set transp=0
  set formatoptions-=tc
  let macvim_hig_shift_movement = 1
endif

if has("gui_win32") || has("gui_win32s")
    set guifont=Consolas:h12
    set enc=utf-8
endif
