" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

filetype on
syntax on

set tabstop=4
set softtabstop=4
set shiftwidth=4
set autoindent
set smartindent
set shiftround
" Ставим табы пробелами
set expandtab

" Make cmdline tab completion similar to bash
set wildmenu
set wildmode=list:longest
set wildignore=*.o,*.obj,*~,*.pyc,*.pyo,*.bak
if v:version >= 703 
    " Make it easier to complete buffers, open files, etc...
    set wildignorecase
endif

set cursorline
set number

" Hide buffers when not displayed
set hidden

" Automaticaly set cwd to opened buffer 
"set autochdir

" Show the cursor position all the time
set ruler

" Jump N lines when running out of the screen
set scrolljump=7
set scrolloff=7
set sidescrolloff=7
set sidescroll=1

" Turn off any bells
set novisualbell
set t_vb=

" Fix <Enter> for comment
set fo+=cr

" Выключаем перенос строк
set nowrap
set nolinebreak

" Отборажение текущей комманды
set showcmd

" Включаем отображение дополнительной информации в статусной строке
set laststatus=2
set statusline=%f%h\ %y\ %m\ %r\ %{&encoding}\ 

" The statusline flag for syntastic plugin
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

set statusline+=%=Line:%l/%L[%p%%]\ Col:%c\ [%b][0x%B]
set statusline+=\ Buf:%n\ 

" Включить подсветку невидимых символов
set list
" Настройка подсветки невидимых символов
set listchars=tab:·\ ,trail:·,extends:»,precedes:«

" Открывать новое окно справа по-вертикали
set splitright

" Set the textwidth to be 80 chars
set textwidth=80

if v:version >= 703
    " mark the ideal max text width
    set colorcolumn=+1
endif


""" ПОИСК

" Включаем подсветку выражения, которое ищется в тексте
set hlsearch
" При поиске перескакивать на найденный текст в процессе набора строки
set incsearch
" Останавливать поиск при достижении конца файла
set nowrapscan
" Игнорировать регистр букв при поиске
set ignorecase


" Размер истории для отмены
set undolevels=100

set encoding=utf-8
" Кодировка по-умолчанию
set termencoding=utf-8
" Список кодировок файлов для автоопределения
set fileencodings=utf-8,cp1251,koi8-r,cp866
" Список форматов файлов
set fileformats=unix,dos,mac

"load ftplugins and indent files
filetype plugin on
filetype indent on

" Метод фолдинга - вручную (для обычных файлов)
"set foldmethod=manual
" Уровень сокрытия по умолчанию для вновь открытых файлов
setlocal foldlevelstart=0
" Метод фолдинга - по синтаксису
setlocal foldmethod=syntax


"" BACKUP

" Отключаем создание бэкапов
set nobackup
" Отключаем создание swap файлов
set noswapfile
" Все swap файлы будут помещаться в эту папку
"set dir=~/.vim/swp


"" DIFF

" Add ignorance of whitespace to diff
set diffopt+=iwhite


"" KEY MAPS

" Очистить подсветку последнего найденного выражения
nmap <F3> :nohlsearch<CR>
imap <F3> <Esc>:nohlsearch<CR>
vmap <F3> <Esc>:nohlsearch<CR>gv

" Дублировать строку после текущей
map <C-A-up> <esc>yyPi
" Дублировать строку перед текущей
map <C-A-down> <esc>yypi

" Auto compleate
imap <C-space> <C-x><C-o>

" Удалить строку
imap <C-d> <esc>ddi

" Starts new line
imap <S-cr> <esc>o
imap <C-S-cr> <esc>O

vmap <C-C> "+yi
imap <C-V> <esc>"+gPi

" Make horizontal scrolling easier
nmap <silent> <C-o> 10zl
nmap <silent> <C-i> 10zh

" Key mapping for saving file
nmap <C-s> :w<CR>

" Add a GUID to the current line
imap <C-J>d <C-r>=substitute(system("uuidgen"), '.$', '', 'g')<CR>


"-------------------------
" GUI
"-------------------------
set background=dark

let g:solarized_termcolors=256
" tell the term has 256 colors
set t_Co=256
colorscheme xoria256

" Set up the gui cursor to look nice
set guicursor=n-v-c:block-Cursor-blinkon0
set guicursor+=ve:ver35-Cursor
set guicursor+=o:hor50-Cursor
set guicursor+=i-ci:ver25-Cursor
set guicursor+=r-cr:hor20-Cursor
set guicursor+=sm:block-Cursor-blinkwait175-blinkoff150-blinkon175


" XML/HTML tags aut complition map
let xml_tag_completion_map = "></"

" New file templates
autocmd BufNewFile *.py 0r ~/.vim/templates/py.tmpl
autocmd BufNewFile *.xml 0r ~/.vim/templates/xml.tmpl
autocmd BufNewFile *.xsl 0r ~/.vim/templates/xsl.tmpl

" Customisations based on filetype
autocmd BufNewFile,BufRead *.rss.*.atom setfiletype xml


"-------------------------
" BufExplorer
"-------------------------

" Show BufExplorer
nnoremap <F5> :BufExplorer<cr>


"-------------------------
" NERD Tree
"-------------------------

" Toggle the NERD Tree on an off
nnoremap <F6> :NERDTreeToggle<cr>
" Store the bookmarks file in perforce
let NERDTreeBookmarksFile="~/.vim/NERDTreeBookmarks"
" Show the bookmarks table on startup
let NERDTreeShowBookmarks=1
" Don't display these kinds of files
let NERDTreeIgnore=['\.pyc$', '\~$']


"-------------------------
" Fugitive
"-------------------------

" Add a mapping on .. to view parent tree
autocmd BufReadPost fugitive://* set bufhidden=delete


"------------------------
" Gundo
" sjl.bitbucket.org/gundo.vim/
"------------------------

nnoremap <F2> :GundoToggle<CR>


"------------------------
" Syntastic
"------------------------

" Use the |:sign| interface to mark syntax errors
let g:syntastic_enable_signs=1


"-----------------------
" Zencoding vim
"-----------------------

let g:user_zen_settings = {
\   'xml' : {
\        'extends' : 'html',
\    },
\   'haml' : {
\        'extends' : 'html',
\    },
\}


"------------------------
" Solarized
"------------------------

let g:solarized_termcolor = 256 

